controller_list:
  - name: "" # If on simulated arm - is actually follow_joint_trajectory
#  - name: "scaled_pos_traj_controller"  # If on actual arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
